name: .NET Build Onl
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: "self-hosted"
    steps:
    - uses: actions/checkout@v4
    # Match and replace 
    - name: "Find and Replace Server name"
      uses: jacobtomlinson/gha-find-replace@v2
      with:
       find: "(SERVERNAME)"
       replace: ${{ secrets.SERVERNAME }}
       regex: false
       include: '**appsettings.template.json'
    - name: "Find and Replace db name"
      uses: jacobtomlinson/gha-find-replace@v2
      with:
       find: "(DBNAME)"
       replace: ${{ secrets.DBNAME }}
       regex: false
       include: '**appsettings.template.json'
    - name: "Find and Replace db user"
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "(DBUSER)"
        replace: ${{ secrets.DBUSER }}
        regex: false
        include: '**appsettings.template.json'
    - name: "Find and Replace db password"
      uses: jacobtomlinson/gha-find-replace@v2
      with:
       find: "(DBPASSWORD)"
       replace: ${{ secrets.DBPASSWORD }}
       regex: false
       include: '**appsettings.template.json'
    - name: "Find and Replace jwtkey"
      uses: jacobtomlinson/gha-find-replace@v2
      with:
       find: "(JWTKEY)"
       replace: ${{ secrets.JWTKEY }}
       regex: false
       include: '**appsettings.template.json'
    - name: "Rename appsettings"
      run: "mv ./TurfManager/appsettings.template.json ./TurfManager/appsettings.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build docker image
      run: "docker build ./TurfManager/TurfManager --file Dockerfile --tag turfmanager:$(date +%s)"

